config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :social_media_accounts
    resources :social_media_marketing_events
    resources :facebook_pages, only: [:create, :destroy, :show]
    resources :social_media_posts, only: [:new, :create, :destroy] do
      collection do
        post :create_with_account
      end
      member do
        put :repost
      end
    end
  end

  get 'auth/:provider/callback', to: 'admin/social_media_accounts#create', as: :oauth_redirect
  get 'auth/facebook', to: 'auth#facebook'
  get 'auth/twitter', to: 'auth#twitter'
  match 'auth/failure', to: redirect('/admin/social_media_accounts'), via: [:get, :post]

end

app/models/spree/social_media_account.rb
module Spree
  class SocialMediaAccount < ActiveRecord::Base
    belongs_to :store, class_name: 'Spree::Product'

    def self.types
      %w(Facebook Twitter)
    end
  end
end

app/controllers/spree/admin/social_media_accounts_controller.rb
module Spree
  module Admin
    class SocialMediaAccountsController < Spree::Admin::ResourceController

      def create
        account_uid = request.env['omniauth.auth']['uid']
        account_type = "Spree::#{request.env['omniauth.auth']['provider'].capitalize}Account"
        token = request.env['omniauth.auth']['credentials']['token']
        if params[:code]
          access_token = Koala::Facebook::OAuth.new.exchange_access_token_info(token)["access_token"]
        else
          access_token = nil
        end
        social_media_account = current_store.social_media_accounts.find_or_initialize_by(uid: account_uid, type: account_type).tap do |account|
          account.assign_attributes(get_media_account_fields)
          if access_token
            account.auth_token = access_token
          else
            account.errors.add(:auth_token, "Missing token")
          end
        end
        if social_media_account.save
          flash[:success] = 'Account Saved'
        else
          flash[:error] = social_media_account.errors.full_messages.join(', ')
        end
        redirect_to admin_social_media_accounts_path
      end

      def show
        if @social_media_account.display_account_name == 'Twitter'
          @posts = @social_media_account.posts.order("created_at desc").page(params[:page]).per(params[:per_page])
        end
      end

      private
        def fetch_social_media
          unless @social_media_account = Spree::SocialMediaAccount.find_by(id: params[:id])
            flash[:alert] = 'Account Does Not Exist'
            redirect_to admin_social_media_accounts_path
          end
        end

        def get_media_account_fields()
          media_account_fields = { auth_token: request.env['omniauth.auth']['credentials']['token'],
                                   name: request.env['omniauth.auth']['info']['name']
                                 }
          if request.env['omniauth.auth']['provider'] == 'twitter'
            media_account_fields.merge!(auth_secret: request.env['omniauth.auth']['credentials']['secret'])
          end

          media_account_fields
        end
    end
  end
end

app/views/spree/admin/social_media_accounts/index.html.erb
<% content_for :page_title do %>
  Social Media Accounts
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:view_linked_events), admin_social_media_marketing_events_path, { class: "btn-success", id: 'view_linked_events_link' } %>
  <%= button_link_to Spree.t(:facebook_account), auth_facebook_url, { class: "btn-success", icon: 'add', id: 'new_facebook_account_link' } %>
  <%= button_link_to Spree.t(:twitter_account), auth_twitter_url, { class: "btn-success", icon: 'add', id: 'new_twitter_account_link' } %>
  <%= button_link_to Spree.t(:new_post), new_admin_social_media_post_path, { class: "btn-success", icon: 'add', id: 'new_post_link' } %>

<% end %>

<div id="social-media-list" data-hook>
  <table class="table" id='listing_social_media_account' data-hook>
    <thead>
      <tr data-hook="social_media_account_header">
        <th><%= Spree.t(:type) %></th>
        <th><%= Spree.t(:account_name) %></th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @social_media_accounts.each do |account| %>
        <tr>
          <td>
            <%= account.display_account_name %>
          </td>
          <td>
            <%= account.name %>
          </td>
          <td>
            <%= link_to admin_social_media_account_path(account), method: :delete, title: 'Remove', class: 'btn btn-danger btn-sm icon-link with-tip action-delete no-text', data: { confirm: 'Are you sure you want to remove this account?', remote: false } do %>
                <span class='icon icon-delete'></span>
              <% end %>
            <%= link_to admin_social_media_account_path(account), title: 'Manage', class: 'btn btn-primary btn-sm icon-link with-tip action-edit no-text' do %>
              <span class='icon icon-cog'></span>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if @social_media_accounts.empty? %>
        <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/admin/social_media_accounts/show.html.erb
<% content_for :page_title do %>
  <%= "#{ @social_media_account.display_account_name } Account" %>
  <%= "for #{ @social_media_account.name }" if @social_media_account.name.present? %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_accounts), admin_social_media_accounts_path, class: 'btn btn-primary' %>
<% end %>

<% if @social_media_account.display_account_name == 'Facebook' %>
  <div class='col-sm-10'>
    <%= form_for [:admin, @social_media_account.pages.build] do |page_form| %>
      <div class="panel panel-default" id="add-facebook-page" data-hook>
        <div class="panel-heading">
          <h1 class="panel-title">
            <%= Spree.t(:add_facebook_page) %>
          </h1>
        </div>
        <div class="panel-body">
          <div data-hook="add_facebook_page_id">

            <div class="col-md-8 col-md-offset-2">
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon3"><%= page_form.label :page_id, 'Facebook Page Id' %></span>
              <%= page_form.hidden_field :account_id, value: @social_media_account.id %>

                <!-- <input class="form-control" aria-label="Text input with multiple buttons" dcvalue=""> -->
                <%= page_form.text_field :page_id, class: 'form-control' %>
                <div class="input-group-btn">
                  <button type="button" class="btn btn-default with-tip" aria-label="Help" title='You can find page id in About section of your page.'>
                    <span class='icon icon-info-sign ' ></span>
                  </button>
                  <%= button Spree.t(:add_page), 'ok', 'submit', { class: 'btn-success', id: 'facebook_page_addition_button', data: { disable_with: 'Adding...' } } %>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    <% end %>
    <div id="facebook-pages-list" data-hook>
      <table class="table" id='listing_facebook_pages' data-hook>
        <thead>
          <tr data-hook="social_media_account_header">
            <th><%= Spree.t(:facebook_page_name) %></th>
            <th class="actions" width="100">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% if @social_media_account.pages.select { |page| page.persisted? }.empty? %>
            <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
          <% else %>
            <% @social_media_account.pages.select { |page| page.persisted? }.each do |page| %>
              <tr>
                <td>
                  <%= page.page_name %>
                </td>
                <td nowrap>
                  <%= link_to admin_facebook_page_path(page), method: :delete, class: 'btn btn-danger btn-sm icon-link with-tip action-delete no-text', title: 'Remove Page', data: { confirm: 'Are you sure you want to remove this page?' } do %>
                    <span class='icon icon-delete'></span>
                  <% end %>
                  <%= link_to admin_facebook_page_path(page), class: 'btn btn-primary btn-sm icon-link with-tip action-edit no-text' do %>
                    <span class='icon icon-cog with-tip' title='Post Content'></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% elsif @social_media_account.display_account_name == 'Twitter' %>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h1 class='panel-title'>
        Post a message on this Twitter Account
      </h1>
    </div>
    <div class='panel-body'>
      <%= form_for [:admin, Spree::SocialMediaPost.new] do |post_form| %>
        <%= render 'spree/admin/social_media_posts/form', { post_form: post_form, social_media_publishable_id: @social_media_account.id, social_media_publishable_type: 'Spree::SocialMediaAccount', limit_message_characters: true } %>
      <% end %>
    </div>
  </div>
  <%= render 'spree/admin/social_media_posts/show', { posts: @posts } %>
<% end %>