config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :social_media_accounts
    resources :social_media_marketing_events
    resources :facebook_pages, only: [:create, :destroy, :show]
    resources :social_media_posts, only: [:new, :create, :destroy] do
      collection do
        post :create_with_account
      end
      member do
        put :repost
      end
    end
  end

  get 'auth/:provider/callback', to: 'admin/social_media_accounts#create', as: :oauth_redirect
  get 'auth/facebook', to: 'auth#facebook'
  get 'auth/twitter', to: 'auth#twitter'
  match 'auth/failure', to: redirect('/admin/social_media_accounts'), via: [:get, :post]

end

app/models/spree/social_media_post.rb
module Spree
  class SocialMediaPost < Spree::Base

    attr_accessor :fb_message, :twitter_message, :fb_accounts, :twitter_accounts

    ## TODO: Can we rename this to social_media_publishable? postable is no word.
    belongs_to :social_media_publishable, polymorphic: true
    belongs_to :user, class_name: 'Spree::User'
    has_many :social_media_post_images, dependent: :destroy
    has_many :images, through: :social_media_post_images, source: :post_image

    ## TODO: Why is this limit present? Should be only for Twitter. Also, extract to a constant.(done)
    ## TODO: Add validations for presence of social_media_publishable
    validates :post_message, presence: true
    validates :post_message, length: { maximum: Spree::TwitterAccount::MAXIMUM_TWEET_LENGTH }, if: :social_media_publishable_is_twitter_account?
    validates :social_media_publishable, presence: true
    accepts_nested_attributes_for :images

    after_create :send_post_and_assign_post_id
    after_destroy :destroy_post_on_social_media, unless: :destroyed_by_association

    def send_post_and_assign_post_id
      begin
        post_id = social_media_publishable.post(post_message, images)
        self.update(post_id: post_id, error_message: nil)
      rescue StandardError => e
        self.update(error_message: e.message)
      end
    end

    def truncate_message(message)
      message.truncate(Spree::TwitterAccount::MAXIMUM_TWEET_LENGTH)
    end

    def create_fb_twitter_posts
      fb_posts = build_posts('facebook')
      twitter_posts = build_posts('twitter')
      save_posts!(fb_posts + twitter_posts)
    end

    def build_posts(social_media)
      posts = []
      get_accounts(social_media).try(:each) do |account_id|
        post = dup
        post.images = images
        post.social_media_publishable = fetch_account(social_media, account_id)
        post.post_message = post.send(:get_message, social_media)
        posts << post
      end
      posts
    end

    def save_posts!(posts)
      Spree::SocialMediaPost.transaction do
        posts.each do |post|
          begin
            post.save!
          rescue ActiveRecord::RecordInvalid => invalid
            return invalid.record.errors
          end
        end
      end
      false
    end

    private

      def fetch_account(social_media, id)
        social_media.eql?('facebook') ? Spree::FacebookPage.find(id) : Spree::TwitterAccount.find(id)
      end

      def get_message(social_media)
        social_media.eql?('facebook') ? fb_message : truncate_message(twitter_message)
      end

      def get_accounts(social_media)
        social_media.eql?('facebook') ? fb_accounts : twitter_accounts
      end

      def destroy_post_on_social_media
        social_media_publishable.remove_post(post_id) if post_id?
      end

      def social_media_publishable_is_twitter_account?
        social_media_publishable.class == Spree::TwitterAccount
      end
  end
end

app/controllers/spree/admin/social_media_posts_controller.rb
module Spree
  module Admin
    class SocialMediaPostsController < Spree::Admin::ResourceController
      before_action :fetch_post, only: [:destroy, :repost]
      before_action :check_social_media_accounts, only: :create_with_account

      def new
        @post = Spree::SocialMediaPost.new
      end

      def create
        @social_media_post = Spree::SocialMediaPost.new(post_params)

        ## TODO: We don't need .present(done)
        if params[:social_media_post][:post_image]
          @social_media_post.images.build(post_image_params)
        end

        if @social_media_post.save
          flash[:success] = 'Post Added'
        else
          flash[:error] = @social_media_post.errors.full_messages.join(', ')
        end
        redirect_back fallback_location: root_path
      end

      def destroy
        if @post.destroy
          flash[:success] = 'Post Removed'
        else
          flash[:error] = 'Could Not Remove Post'
        end
        redirect_back fallback_location: root_path
      end

      def repost
        @post.send_post_and_assign_post_id
        redirect_back fallback_location: root_path
      end

      def create_with_account
        @post = Spree::SocialMediaPost.new(post_with_account_params)
        @post.images.build(post_image_params) if params[:social_media_post][:post_image]
        response = @post.create_fb_twitter_posts
        if response.instance_of?(ActiveModel::Errors)
          flash[:error] = response.full_messages.join(', ')
          render :new
        else
          flash[:success] = 'Post Added'
          redirect_to new_admin_social_media_post_path
        end
      end

      private

        def fetch_post
          unless @post = Spree::SocialMediaPost.find_by(id: params[:id])
            flash[:alert] = 'Post Does Not Exist'
            redirect_back fallback_location: root_path
          end
        end

        def post_params
          params.require(:social_media_post).permit(:post_message, :social_media_publishable_id, :social_media_publishable_type).merge(user_id: try_spree_current_user.id)
        end

        def post_with_account_params
          params.require(:social_media_post).permit(:post_message, :social_media_publishable_id, :social_media_publishable_type, :fb_message, :twitter_message, fb_accounts: [], twitter_accounts: []).merge(user_id: try_spree_current_user.id)
        end

        def post_image_params
          params.require(:social_media_post).require(:post_image).permit(:attachment)
        end

        def post_fb_accounts_params
          params.require(:social_media_post).permit(fb_accounts: [])
        end

        def post_twitter_accounts_params
          params.require(:social_media_post).permit(twitter_accounts: [])
        end

        def check_social_media_accounts
          if post_fb_accounts_params.empty? && post_twitter_accounts_params.empty?
            flash[:error] = 'Please select accounts'
            render :new
          end
        end
    end
  end
end

app/helpers/spree/admin/social_media_posts_helper.rb
module Spree
  module Admin
    module SocialMediaPostsHelper
      def get_all_social_media_accounts
        Spree::FacebookPage.all + Spree::TwitterAccount.all
      end

      def set_checked(id, accounts_array)
        accounts_array.include?(id) if accounts_array.present?
      end

      def display_account_name_with_social_platform(media_account)
        media_account.instance_of?(Spree::FacebookPage) ? "Facebook - #{ display_account_name(media_account) }" : "Twitter - #{ display_account_name(media_account) }"
      end

      def display_account_name(media_account)
        if media_account.instance_of?(Spree::FacebookPage)
          media_account.account.name + '/' + media_account.page_name
        else
          media_account.name
        end
      end
    end
  end
end

app/views/spree/admin/social_media_posts/_form.html.erb
<%= post_form.hidden_field :social_media_publishable_id, value: social_media_publishable_id %>
<%= post_form.hidden_field :social_media_publishable_type, value: social_media_publishable_type %>
<div>
  <div class="row no-padding">
    <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <%= post_form.fields_for post_form.object.images.build do |image_form| %>
          <div data-hook="file">
            <%= image_form.label :attachment, Spree.t(:image) %>
            <%= image_form.file_field :attachment %>
          </div>
          <br><span> Upto <%= Spree::PostImage::MAXIMUM_IMAGE_SIZE %>MB </span>
        <% end %>
      </div>
      <div class="col-md-8">
        <div data-hook="message"=>
          <%= post_form.label :post_message, 'Message' %> <span class="required">*</span>
          <%= post_form.text_area :post_message, class: "form-control #{ 'character-limited' if limit_message_characters }", rows: 4, data: { character_limit: Spree::TwitterAccount::MAXIMUM_TWEET_LENGTH, remove_dynamic_code: false } %>
          <% if limit_message_characters %>
            <div class="remaining_character_block text-right">
              <span id='remaining_character_span'></span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    </div>
  </div>

</div>
<div class="text-right">
  <%= button Spree.t(:submit_new_post), 'ok', 'submit', { class: 'btn-success', data: { disable_with: 'Submitting...' } } %>
</div>

app/views/spree/admin/social_media_posts/_show.html.erb
<div id="posts-list" data-hook>
  <h4>
    Recent Posts
  </h4>
  <% if posts.empty? %>
    <h5>You have no posts for this account.</h5>
  <% else %>
    <table class="table" id='listing_pages' data-hook>
      <thead>
        <tr data-hook="social_media_publishable_header">
          <th><%= Spree.t(:s_no) %></th>
          <th><%= Spree.t(:post) %></th>
          <th><%= Spree.t(:image) %></th>
          <th><%= Spree.t(:error) %></th>
          <th><%= Spree.t(:posted_by) %></th>
          <th><%= Spree.t(:posted_at) %></th>
          <th class="actions">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% posts.each.with_index(1) do |post, index| %>
          <tr>
            <td>
              <%= index %>
            </td>
            <td class='social-media-post-message-column'>
              <%= post.post_message %>
            </td>
            <td>
              <%= image_tag post.images.first.attachment.url(:mini) if post.images.exists? %>
            </td>
            <td class='social-media-post-error-message-column'>
              <%= post.error_message %>
            </td>
            <td>
              <%= post.user.try(:email) %>
            </td>
            <td>
              <%= post.created_at.strftime('%Y-%m-%d %I:%M %p') %>
            </td>
            <td>
              <%= link_to admin_social_media_post_path(post), method: :delete, title: 'Remove Post', class: 'btn btn-danger btn-sm icon-link with-tip action-delete no-text', data: { confirm: 'Are you sure you want to remove this post?', remote: false } do %>
                <span class='icon icon-delete'></span>
              <% end %>
              <% unless post.post_id %>
                <%= link_to repost_admin_social_media_post_path(post), method: :put, title: 'Repost', class: 'btn btn-primary btn-sm icon-link with-tip no-text', data: { remote: false } do %>
                  <span class='icon icon-retweet'></span>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: posts } %>
  <% end %>
</div>

app/views/spree/admin/social_media_posts/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:new_post), new_admin_social_media_post_path %>
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_accounts), admin_social_media_accounts_path, class: 'btn btn-primary' %>
<% end %>

<%= form_for(@post, url: create_with_account_admin_social_media_posts_path) do |post_form| %>
  <div class="row no-padding">
    <div class="col-md-9">
    <div class="row">
      <div class="col-md-4">
        <%= post_form.fields_for post_form.object.images.build do |image_form| %>
          <div data-hook="file">
            <%= image_form.label :attachment, Spree.t(:image) %>
            <%= image_form.file_field :attachment %>
          </div><br>
          <span> Upto <%= Spree::PostImage::MAXIMUM_IMAGE_SIZE %>MB </span>
        <% end %>
      </div>
      <div class="col-md-8">
        <div data-hook="message"=>
          <%= post_form.label :post_message, 'Message' %> <span class="required">*</span>
          <%= post_form.text_area :post_message, class: "form-control message", rows: 4, data: { remove_dynamic_code: false } %>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <div class='row no-padding'>
      <div class='col-md-12'>
        <div data-hook="fb_message">
          <%= post_form.label :fb_message, 'Facebook Message' %>
          <%= post_form.text_area :fb_message, class: "form-control fb-message", rows: 4 %>
        </div>
        <div data-hook="twitter_message">
          <%= post_form.label :twitter_message, 'Twitter Message' %>
          <%= post_form.text_area :twitter_message, class: "form-control twitter-message character-limited", rows: 4, data: { character_limit: Spree::TwitterAccount::MAXIMUM_TWEET_LENGTH } %>
          <div class="remaining_character_block text-right" id='event-message-remaining-charachter-block'>
            <span id='remaining_character_span'></span>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <table class="table table-condensed table-bordered index socail-media-accounts-table">
        <thead>
          <tr data-hook="rma_header">
            <th></th>
            <th><%= Spree.t(:account_name) %></th>
          </tr>
        </thead>
        <tbody>
          <% get_all_social_media_accounts.each do |account| %>
          <tr data-type='social-media-accounts'>
            <td>
              <% if account.instance_of?(Spree::FacebookPage) %>
                <%= post_form.check_box :fb_accounts, { multiple: true, checked: set_checked(account.id.to_s, post_form.object.fb_accounts), data: { type: 'fb-account', name: display_account_name(account) } } , account.id, false %>
              <% else %>
                <%= post_form.check_box :twitter_accounts, { multiple: true, checked: set_checked(account.id.to_s, post_form.object.twitter_accounts), data: { type: 'twitter-account', name: display_account_name(account) } }, account.id, false %>
              <% end %>
            </td>
            <td>
              <%= display_account_name_with_social_platform(account) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= button Spree.t(:submit_new_post), 'ok', 'button', { class: 'btn-success', data: { toggle: 'modal', target: '#confirm_publish', type: 'confirm-modal' } } %>
  <%= button_link_to Spree.t('actions.cancel'), admin_social_media_accounts_path, :icon => 'delete' %>

  <!-- Modal -->
  <div class="modal fade" id="confirm_publish" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Confirm</h4>
        </div>
        <div class="modal-body">
          <p data-type='error-message'>Please select accounts and Try Again</p>
          <p data-type='confirm-message'>Post will be posted on the following accounts:- </p>
          <p data-container='fb_accounts'></p>
          <p data-container='twitter_accounts'></p>
        </div>
        <div class="modal-footer">
          <%= button Spree.t(:submit_new_post), 'ok', 'submit', { class: 'btn-success', data: { disable_with: 'Submitting...', type: 'form-button' } } %>
          <%= button Spree.t(:close), '', 'button', { class: 'btn-default', data: { dismiss: 'modal' } } %>
        </div>
      </div>
    </div>
  </div>

<% end %>