config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :social_media_accounts
    resources :social_media_marketing_events
    resources :facebook_pages, only: [:create, :destroy, :show]
    resources :social_media_posts, only: [:new, :create, :destroy] do
      collection do
        post :create_with_account
      end
      member do
        put :repost
      end
    end
  end

  get 'auth/:provider/callback', to: 'admin/social_media_accounts#create', as: :oauth_redirect
  get 'auth/facebook', to: 'auth#facebook'
  get 'auth/twitter', to: 'auth#twitter'
  match 'auth/failure', to: redirect('/admin/social_media_accounts'), via: [:get, :post]

end

app/models/spree/social_media_marketing_event.rb
module Spree
  class SocialMediaMarketingEvent < ActiveRecord::Base

    TWITTER_MESSAGE_MAXIMUM_LENGTH = 240

    validates :fb_message, :twitter_message, presence: true
    validate :can_be_activated, if: :active_and_active_changed?
    validate :message_without_methods_does_not_exceed_maxinmum_length
    validate :check_fb_message, if: :fb_message_changed?
    validate :check_twitter_message, if: :twitter_message_changed?

    has_many :social_media_events_accounts, class_name: 'Spree::SocialMediaEventsAccount'
    has_many :facebook_accounts, through: :social_media_events_accounts, source: :social_media_marketing_account, source_type: 'Spree::FacebookPage'
    has_many :twitter_accounts, through: :social_media_events_accounts, source: :social_media_marketing_account, source_type: 'Spree::SocialMediaAccount'

    accepts_nested_attributes_for :social_media_events_accounts, allow_destroy: true

    def get_parsed_message(instance, type='facebook', options = {})
      parse_string(get_instance_methods(type), instance, type, options)
    end

    def linked_social_media_accounts
      facebook_accounts + twitter_accounts
    end

    def all_social_media_accounts
      Spree::FacebookPage.all + Spree::TwitterAccount.all
    end

    def unlinked_social_media_accounts
      all_social_media_accounts - linked_social_media_accounts
    end

    private
      def parse_string(methods, instance, type='facebook', options = {})
        message = type.eql?('facebook') ? fb_message : twitter_message
        parsed_message = message.dup
        methods.each do |method|
          method_name = method[1, (method.length - 2)]
          parsed_message.gsub!(method, (options[method_name.to_sym] || instance.send(method_name)) || '')
        end
        parsed_message
      end

      def message_without_methods_does_not_exceed_maxinmum_length
        if twitter_message.gsub(/<.*?>/, '').length > TWITTER_MESSAGE_MAXIMUM_LENGTH
          errors.add(:twitter_message, "without dynamic content can not be more than #{ TWITTER_MESSAGE_MAXIMUM_LENGTH } characters long")
        end
      end

      def get_instance_methods(type='facebook')
        message = type.eql?('facebook') ? fb_message : twitter_message
        methods = message.scan(/(<.*?>)/).flatten.uniq
      end

      def check_fb_message
        message_is_parsable('facebook')
      end

      def check_twitter_message
        message_is_parsable('twitter')
      end

      def message_is_parsable(type)
        begin
          klass = eval(class_to_run)
          if klass.respond_to?(:get_social_marketing_message)
            get_parsed_message(klass, type)
          elsif klass.new.respond_to?(:get_social_marketing_message)
            get_parsed_message(klass.new, type)
          end
        rescue StandardError => e
          errors.add(:base, 'Some of the methods used in the message are not valid. Please check the methods list.')
        end
      end

      def can_be_activated
        if run_time == 'future' && Rails.application.config.active_job.queue_adapter == :inline
          errors.add(:base, 'To activate this event, you need a queueing backend adapter, which is not implemented for this app. Please contact your developer.')
        end
      end

      def active_and_active_changed?
        active_changed? and active?
      end
  end
end

app/controllers/spree/admin/social_media_marketing_events_controller.rb
module Spree
  module Admin
    class SocialMediaMarketingEventsController < Spree::Admin::ResourceController
      helper 'spree/admin/social_media_marketing_events'

      def edit
        @social_media_marketing_event.unlinked_social_media_accounts.each do |account|
          @social_media_marketing_event.social_media_events_accounts.build(social_media_marketing_account: account)
        end
      end

      def create
      end

      def show
      end

      private

        def social_media_marketing_event_params
          params.require(:social_media_marketing_event).permit(:message, :active, :threshold)
        end
    end
  end
end

app/helpers/spree/admin/social_media_marketing_events_helper.rb
module Spree
  module Admin
    module SocialMediaMarketingEventsHelper

      def display_account_name(event_account)
        if event_account.facebook?
          'Facebook - ' + event_account.social_media_marketing_account.account.name + '/' + event_account.social_media_marketing_account.page_name
        else
          'Twitter - ' + event_account.social_media_marketing_account.name
        end
      end
    end
  end
end

app/views/spree/admin/social_media_marketing_events/_form.html.erb
<div data-hook="admin_social_media_marketing_event_form_fields">

  <div data-hook="social_media_marketing_event" class="row">
    <div class="col-md-9">
      <div class='row'>
      <div class='col-md-12'>
        <div data-hook="name" class="form-group">
          <%= label_tag :social_media_marketing_event_name, Spree.t(:name) %>:
          <b><%= @social_media_marketing_event.name.titleize %></b>
        </div>
      </div>
      </div>
      <div class='row no-padding'>
        <div class="col-md-12">
          <% class_to_run = eval(@social_media_marketing_event.class_to_run) %>
          <% if class_to_run::MARKUP_ALLOWED_METHODS.present? %>
            <p>
              Type the default post for <%= @social_media_marketing_event.name.titleize %> message. You can also add dynamic content to it by using simple markup.
            </p>
            <p>Example: &lt;method_name&gt;. <a data-toggle="collapse" data-target="#usable_methods_div" id='show-available-methods-link'>Show available methods.</a>
            </p>

            <div id="usable_methods_div" class="collapse">
              <ul>
                <% class_to_run::MARKUP_ALLOWED_METHODS.each do |method| %>
                  <li>
                    <%= method %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
        <div class="col-md-12 form-group" data-hook="fb_message">
          <%= label_tag :social_media_marketing_event_message, Spree.t(:fb_message) %>
          <%= text_area :social_media_marketing_event, :fb_message, { :cols => 50, :rows => 4, :class => 'form-control social_media_post_message', data: { remove_dynamic_code: true } } %>
        </div>
        <div class="col-md-12 form-group" data-hook="twitter_message">
          <%= label_tag :social_media_marketing_event_message, Spree.t(:twitter_message) %>
          <%= text_area :social_media_marketing_event, :twitter_message, { :cols => 50, :rows => 4, :class => 'form-control social_media_post_message character-limited', data: { character_limit: Spree::SocialMediaMarketingEvent::TWITTER_MESSAGE_MAXIMUM_LENGTH, remove_dynamic_code: true } } %>
          <div class="remaining_character_block text-right" id='event-message-remaining-charachter-block'>
            <span id='remaining_character_span'></span>
          </div>
        </div>
      </div>
      <div class="row no-padding">
        <div class="col-md-12">
          <table class="table table-condensed table-bordered index social-media-account-table">
            <thead>
              <tr data-hook="rma_header">
                <th></th>
                <th><%= Spree.t(:account_name) %></th>
              </tr>
            </thead>
            <tbody>
              <%= f.fields_for :social_media_events_accounts do |q| %>
                <% events_account = q.object %>
                <tr>
                  <td>
                    <%= q.check_box :_destroy, { checked: events_account.persisted? }, '0', '1' %>
                    <%= q.hidden_field :social_media_marketing_account_id  %>
                    <%= q.hidden_field :social_media_marketing_account_type  %>
                  </td>
                  <td>
                    <div class="account-name">
                      <%= display_account_name(events_account) %>
                    </div>
                  </td>
              <% end %>
            </tbody>
          </table>
          <div data-hook="active" class="form-group">
            <span class="check-box">
              <%= check_box :social_media_marketing_event, :active %>
            </span>
            <%= label_tag :social_media_marketing_event_active, Spree.t(:active) %>
          </div>

        </div>

      </div>

    </div>
  </div>
  <div class='row'>
    <div class="col-md-4">
      <% if @social_media_marketing_event.name.match(/ Milestone$/) %>
        <div data-hook="active" class="form-group">
          <%= label_tag :social_media_marketing_event_threshold, Spree.t(:milestone) %>
          <div class='input'>
            <%= f.number_field :threshold, class: 'form-control' %>
          </div>
        </div>
      <% elsif @social_media_marketing_event.name == 'Low Stock Products' %>
        <div data-hook="active" class="form-group">
          <%= label_tag :social_media_marketing_event_threshold, Spree.t(:low_stock_threshold) %>
          <div class='input'>
            <%= f.number_field :threshold, class: 'form-control' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/social_media_marketing_events/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:Events), admin_social_media_marketing_events_path %> /
  <%= @social_media_marketing_event.name %>
<% end %>

<%= form_for @social_media_marketing_event, url: admin_social_media_marketing_event_path(@social_media_marketing_event) do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/social_media_marketing_events/index.html.erb
<% content_for :page_title do %>
  Social Media Marketing Events
<% end %>

<% content_for :page_actions do %>
  <%= link_to_with_icon 'arrow-left', Spree.t(:back_to_accounts), admin_social_media_accounts_path, class: 'btn btn-primary' %>
<% end %>

<div id="social-media-marketing-event-list" data-hook>
  <table class="table" id='listing_social_media_marketing_events' data-hook>
    <thead>
      <tr data-hook="social_media_marketing_event_header">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:active) %></th>
        <th class="actions">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @social_media_marketing_events.each do |marketing_event| %>
        <tr>
          <td>
            <%= marketing_event.name.titleize %>
          </td>
          <td>
            <%= marketing_event.active? ? 'Yes' : 'No' %>
          </td>
          <td>
            <%= link_to edit_admin_social_media_marketing_event_path(marketing_event), title: 'Manage', class: 'btn btn-primary btn-sm icon-link with-tip action-edit no-text' do %>
              <span class='icon icon-cog'></span>
            <% end %>
          </td>
        </tr>
      <% end %>
      <% if @social_media_marketing_events.empty? %>
        <tr><td colspan="3"><%= Spree.t(:none) %></td></tr>
      <% end %>
    </tbody>
  </table>
</div>